### ISSUE TITLE
Allow only alphabetical characters as input (remove digits, punctuation, spaces etc)

### ISSUE THREAD

**Issue by matheusportela** [matheusportela/enigma-machine#11]

**Comment by rafael-telles** [comment]
You can use HTML5's form validation, you just need to wrap inputs into a `<form />` and add the attribute `pattern` to the first `<input>` element with some regex (maybe `pattern="[a-zA-Z]+"`).

Reference: http://www.w3schools.com/tags/att_input_pattern.asp
